// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Token struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
	UserAgent sql.NullString
	IpAddress sql.NullString
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Phone     string
	Avatar    sql.NullString
	Type      string
	Password  string
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
